name: 'Data Validator'
description: 'Validate data files.'
inputs:
  configuration:
    description: 'URL of the configuration.'
    required: true
  path:
    description: 'Path to file or a directory to validate.'
    required: false
    default: '/github/workspace'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/datagov-cz/data-validator:develop'
  args:
    - -c=${{ inputs.configuration }}
    - -p=${{ inputs.path }}
